//
// Generated by JTB 1.3.2
// Modified to check for final variable assignments and uninitialized variables
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 *
 * This version performs a single-pass check for:
 * 1) Assigning to a final variable (after its declaration initializer)
 * 2) Using an uninitialized variable
 *
 * Strategy:
 * - finalVars: names declared with "final" in the current method scope
 * - initializedVars: names that have been assigned / are params / are finals
 * (finals are initialized at declaration)
 * - localVars: names declared with SimpleVarDeclaration inside a method
 * (these start uninitialized)
 * - inMethodScope: true while inside a MethodDeclaration body
 * - inLHSContext: true when visiting the LHS Identifier of an assignment
 * so we do NOT treat it as a "read" use
 *
 * Class-level SimpleVarDeclarations (fields) are NOT tracked for uninitialized
 * use because BuritoJava only requires checking local variables.
 */
public class LLM<R, A> implements GJVisitor<R, A> {

  // -------------------------------------------------------------------------
  // State for variable checking
  // -------------------------------------------------------------------------
  private Set<String> finalVars = new HashSet<String>();
  private Set<String> initializedVars = new HashSet<String>();
  private Set<String> localVars = new HashSet<String>();

  private boolean inMethodScope = false;
  private boolean inLHSContext = false;

  private boolean finalAssigned = false;
  private boolean uninitializedUsed = false;

  public boolean hasFinalAssignment() {
    return finalAssigned;
  }

  public boolean hasUninitializedUse() {
    return uninitializedUsed;
  }

  // -------------------------------------------------------------------------
  // Auto class visitors -- probably don't need to be overridden.
  // -------------------------------------------------------------------------
  public R visit(NodeList n, A argu) {
    R _ret = null;
    int _count = 0;
    for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
      e.nextElement().accept(this, argu);
      _count++;
    }
    return _ret;
  }

  public R visit(NodeListOptional n, A argu) {
    if (n.present()) {
      R _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
        e.nextElement().accept(this, argu);
        _count++;
      }
      return _ret;
    } else
      return null;
  }

  public R visit(NodeOptional n, A argu) {
    if (n.present())
      return n.node.accept(this, argu);
    else
      return null;
  }

  public R visit(NodeSequence n, A argu) {
    R _ret = null;
    int _count = 0;
    for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
      e.nextElement().accept(this, argu);
      _count++;
    }
    return _ret;
  }

  public R visit(NodeToken n, A argu) {
    return null;
  }

  //
  // User-generated visitor methods below
  //

  /**
   * f0 -> MainClass()
   * f1 -> ( TypeDeclaration() )*
   * f2 -> <EOF>
   */
  public R visit(Goal n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f1.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "class"
   * f1 -> Identifier()
   * f2 -> "{"
   * f3 -> "public"
   * f4 -> "static"
   * f5 -> "void"
   * f6 -> "main"
   * f7 -> "("
   * f8 -> "String"
   * f9 -> "["
   * f10 -> "]"
   * f11 -> Identifier()
   * f12 -> ")"
   * f13 -> "{"
   * f14 -> PrintStatement()
   * f15 -> "}"
   * f16 -> "}"
   */
  public R visit(MainClass n, A argu) {
    R _ret = null;
    // f11 is the "args" parameter name -- not tracked
    // f14 is the single PrintStatement -- visit it but no locals here
    n.f14.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> ClassDeclaration()
   * | ClassExtendsDeclaration()
   */
  public R visit(TypeDeclaration n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "class"
   * f1 -> Identifier()
   * f2 -> "{"
   * f3 -> ( SimpleVarDeclaration() )*
   * f4 -> ( MethodDeclaration() )*
   * f5 -> "}"
   */
  public R visit(ClassDeclaration n, A argu) {
    R _ret = null;
    // Class fields are default-initialized in Java (null/0/false).
    // Only local variables inside methods need uninitialized tracking.
    // Skip f3 (field declarations) and just visit methods.
    n.f4.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "class"
   * f1 -> Identifier()
   * f2 -> "extends"
   * f3 -> Identifier()
   * f4 -> "{"
   * f5 -> ( SimpleVarDeclaration() )*
   * f6 -> ( MethodDeclaration() )*
   * f7 -> "}"
   */
  public R visit(ClassExtendsDeclaration n, A argu) {
    R _ret = null;
    // Same as ClassDeclaration: skip fields, just visit methods.
    n.f6.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> SimpleVarDeclaration()
   * | FinalVarDeclaration()
   */
  public R visit(VarDeclaration n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> Type()
   * f1 -> Identifier()
   * f2 -> ";"
   *
   * When inside a method: this variable starts UNINITIALIZED (local var).
   * When at class level: add to classFields so every method in this class
   * knows the field exists but is uninitialized.
   */
  public R visit(SimpleVarDeclaration n, A argu) {
    R _ret = null;
    // Only track variables declared inside methods.
    // Class-level fields are always default-initialized (Java semantics).
    if (inMethodScope) {
      String name = n.f1.f0.tokenImage;
      localVars.add(name);
      // NOT added to initializedVars -- it starts uninitialized
    }
    return _ret;
  }

  /**
   * f0 -> "final"
   * f1 -> Type()
   * f2 -> Identifier()
   * f3 -> "="
   * f4 -> Expression()
   * f5 -> ";"
   *
   * Final vars are ALWAYS initialized at declaration (grammar requires it).
   * Check the RHS expression for uninitialized reads, then mark as initialized.
   */
  public R visit(FinalVarDeclaration n, A argu) {
    R _ret = null;
    String name = n.f2.f0.tokenImage;
    // Visit RHS expression first (may read other variables)
    n.f4.accept(this, argu);
    // Now mark this final as declared and initialized
    if (inMethodScope) {
      localVars.add(name);
      finalVars.add(name);
      initializedVars.add(name);
    }
    return _ret;
  }

  /**
   * f0 -> "public"
   * f1 -> Type()
   * f2 -> Identifier()
   * f3 -> "("
   * f4 -> ( FormalParameterList() )?
   * f5 -> ")"
   * f6 -> "{"
   * f7 -> ( VarDeclaration() )*
   * f8 -> ( Statement() )*
   * f9 -> "return"
   * f10 -> Expression()
   * f11 -> ";"
   * f12 -> "}"
   */
  public R visit(MethodDeclaration n, A argu) {
    R _ret = null;

    // Save outer scope
    Set<String> savedFinals = finalVars;
    Set<String> savedInitialized = initializedVars;
    Set<String> savedLocals = localVars;
    boolean savedInMethod = inMethodScope;

    finalVars = new HashSet<String>();
    initializedVars = new HashSet<String>();
    localVars = new HashSet<String>(); // only method-local vars
    inMethodScope = true;

    // Visit formal parameters (they are initialized)
    n.f4.accept(this, argu); // ( FormalParameterList() )?

    // Visit var declarations (populates localVars / finalVars)
    n.f7.accept(this, argu); // ( VarDeclaration() )*

    // Visit statements (checks assignments and reads)
    n.f8.accept(this, argu); // ( Statement() )*

    // Visit return expression (check for uninitialized reads)
    n.f10.accept(this, argu); // Expression()

    // Restore
    finalVars = savedFinals;
    initializedVars = savedInitialized;
    localVars = savedLocals;
    inMethodScope = savedInMethod;

    return _ret;
  }

  /**
   * f0 -> FormalParameter()
   * f1 -> ( FormalParameterRest() )*
   */
  public R visit(FormalParameterList n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> Type()
   * f1 -> Identifier()
   *
   * Parameters are always initialized.
   */
  public R visit(FormalParameter n, A argu) {
    R _ret = null;
    String name = n.f1.f0.tokenImage;
    localVars.add(name);
    initializedVars.add(name);
    return _ret;
  }

  /**
   * f0 -> ","
   * f1 -> FormalParameter()
   */
  public R visit(FormalParameterRest n, A argu) {
    R _ret = null;
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> ArrayType()
   * | BooleanType()
   * | IntegerType()
   * | Identifier()
   */
  public R visit(Type n, A argu) {
    R _ret = null;
    // Do NOT recurse -- the Identifier inside a Type is a type name, not a variable
    return _ret;
  }

  /**
   * f0 -> "int"
   * f1 -> "["
   * f2 -> "]"
   */
  public R visit(ArrayType n, A argu) {
    return null;
  }

  /**
   * f0 -> "boolean"
   */
  public R visit(BooleanType n, A argu) {
    return null;
  }

  /**
   * f0 -> "int"
   */
  public R visit(IntegerType n, A argu) {
    return null;
  }

  /**
   * f0 -> Block()
   * | AssignmentStatement()
   * | ArrayAssignmentStatement()
   * | FieldAssignmentStatement()
   * | IfStatement()
   * | WhileStatement()
   * | ForStatement()
   * | PrintStatement()
   */
  public R visit(Statement n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "{"
   * f1 -> ( Statement() )*
   * f2 -> "}"
   */
  public R visit(Block n, A argu) {
    R _ret = null;
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> Identifier() <-- LHS (write)
   * f1 -> "="
   * f2 -> Expression() <-- RHS (read)
   * f3 -> ";"
   *
   * Check:
   * 1. If LHS is a final var that's already initialized -> error
   * 2. Visit RHS for uninitialized reads
   * 3. Mark LHS as initialized
   */
  public R visit(AssignmentStatement n, A argu) {
    R _ret = null;
    String lhs = n.f0.f0.tokenImage;

    // Check if assigning to a final
    if (finalVars.contains(lhs)) {
      finalAssigned = true;
      return _ret;
    }

    // Visit RHS -- check for uninitialized reads
    n.f2.accept(this, argu);

    // Mark LHS as initialized (only if it's a local var we're tracking)
    if (localVars.contains(lhs)) {
      initializedVars.add(lhs);
    }

    return _ret;
  }

  /**
   * f0 -> Identifier() <-- array variable (read: must be initialized)
   * f1 -> "["
   * f2 -> Expression() <-- index expression
   * f3 -> "]"
   * f4 -> "="
   * f5 -> Expression() <-- value expression
   * f6 -> ";"
   *
   * The array variable itself is being READ (to find the array), then an
   * element is written. So the array var must be initialized.
   * This is NOT an assignment to a final array var (elements are being set,
   * not the variable itself being rebound), BUT if someone wrote
   * finalArr[i] = x;
   * the grammar still parses it as ArrayAssignmentStatement.
   * Per spec: "explicit assignments to final variables" -- this modifies
   * array contents, not the variable binding, so we do NOT flag it as
   * a final assignment. We just check the array var is initialized.
   */
  public R visit(ArrayAssignmentStatement n, A argu) {
    R _ret = null;
    String arrName = n.f0.f0.tokenImage;

    // The array variable must be initialized to use it
    if (localVars.contains(arrName) && !initializedVars.contains(arrName)) {
      uninitializedUsed = true;
      return _ret;
    }

    // Visit index and value expressions
    n.f2.accept(this, argu);
    n.f5.accept(this, argu);

    return _ret;
  }

  /**
   * f0 -> Expression() <-- object expression (e.g. this, or a variable)
   * f1 -> "."
   * f2 -> Identifier() <-- field name (NOT a local variable)
   * f3 -> "="
   * f4 -> Expression()
   * f5 -> ";"
   *
   * The field name (f2) is not a local variable. We only check f0 and f4.
   */
  public R visit(FieldAssignmentStatement n, A argu) {
    R _ret = null;
    // Visit object expression (may read local vars, e.g. "this")
    n.f0.accept(this, argu);
    // Skip f2 (field name -- not a local variable reference)
    // Visit value expression
    n.f4.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "if"
   * f1 -> "("
   * f2 -> Expression()
   * f3 -> ")"
   * f4 -> Statement() <-- then-branch
   * f5 -> "else"
   * f6 -> Statement() <-- else-branch
   *
   * A variable is definitely initialized after an if-else only if it is
   * initialized in BOTH branches. We compute each branch's initialized set
   * independently and take their intersection (merged with what was already
   * initialized before).
   */
  public R visit(IfStatement n, A argu) {
    R _ret = null;
    // Visit condition
    n.f2.accept(this, argu);

    // Snapshot the state entering both branches
    Set<String> beforeBranches = new HashSet<String>(initializedVars);

    // Visit then-branch
    n.f4.accept(this, argu);
    Set<String> afterThen = new HashSet<String>(initializedVars);

    // Reset to pre-branch state, visit else-branch
    initializedVars = new HashSet<String>(beforeBranches);
    n.f6.accept(this, argu);
    Set<String> afterElse = new HashSet<String>(initializedVars);

    // After if-else: only vars initialized in BOTH branches are definite
    afterThen.retainAll(afterElse); // intersection
    initializedVars = afterThen;

    return _ret;
  }

  /**
   * f0 -> "while"
   * f1 -> "("
   * f2 -> Expression()
   * f3 -> ")"
   * f4 -> Statement()
   *
   * The loop body may execute zero times, so any variable first assigned
   * inside the body is NOT definitely initialized after the loop.
   * We snapshot initializedVars before the body and restore it after,
   * but still visit the body so we catch reads of uninitialized vars inside.
   */
  public R visit(WhileStatement n, A argu) {
    R _ret = null;
    // Visit condition (reads here use the pre-loop initialized set)
    n.f2.accept(this, argu);

    // Snapshot before body -- the body may not execute at all
    Set<String> beforeBody = new HashSet<String>(initializedVars);

    // Visit body (detects uninitialized reads inside the loop)
    n.f4.accept(this, argu);

    // Restore: assignments inside the body don't count as definite
    initializedVars = beforeBody;

    return _ret;
  }

  /**
   * f0 -> "for"
   * f1 -> "("
   * f2 -> Identifier() <-- init LHS (write -- ALWAYS executes)
   * f3 -> "="
   * f4 -> Expression() <-- init RHS (read)
   * f5 -> ";"
   * f6 -> Expression() <-- condition (read)
   * f7 -> ";"
   * f8 -> Identifier() <-- update LHS (write -- may not execute)
   * f9 -> "="
   * f10 -> Expression() <-- update RHS (read -- may not execute)
   * f11 -> ")"
   * f12 -> Statement() <-- body (may not execute)
   *
   * The init part (f2=f4) definitely executes. The condition (f6) definitely
   * executes. The body (f12) and update (f8=f10) may not execute if the
   * condition is false from the start. So we snapshot before the body+update
   * and restore initializedVars after.
   */
  public R visit(ForStatement n, A argu) {
    R _ret = null;

    String initVar = n.f2.f0.tokenImage;
    String updateVar = n.f8.f0.tokenImage;

    // Init assignment -- always executes
    if (finalVars.contains(initVar)) {
      finalAssigned = true;
      return _ret;
    }
    n.f4.accept(this, argu); // init RHS
    if (localVars.contains(initVar)) {
      initializedVars.add(initVar);
    }

    // Condition -- always executes (at least once)
    n.f6.accept(this, argu);

    // Snapshot before body+update -- they may not execute
    Set<String> beforeLoop = new HashSet<String>(initializedVars);

    // Check update assignment (may assign a final)
    if (finalVars.contains(updateVar)) {
      finalAssigned = true;
      return _ret;
    }
    // Visit body
    n.f12.accept(this, argu);

    // Visit update RHS and mark update var (still inside "may not run" zone)
    n.f10.accept(this, argu);
    if (localVars.contains(updateVar)) {
      initializedVars.add(updateVar);
    }

    // Restore: body+update assignments are not definite
    initializedVars = beforeLoop;

    return _ret;
  }

  /**
   * f0 -> "System.out.println"
   * f1 -> "("
   * f2 -> Expression()
   * f3 -> ")"
   * f4 -> ";"
   */
  public R visit(PrintStatement n, A argu) {
    R _ret = null;
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> AndExpression()
   * | CompareExpression()
   * | PlusExpression()
   * | MinusExpression()
   * | TimesExpression()
   * | ArrayLookup()
   * | ArrayLength()
   * | MessageSend()
   * | PrimaryExpression()
   */
  public R visit(Expression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "&"
   * f2 -> PrimaryExpression()
   */
  public R visit(AndExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "<"
   * f2 -> PrimaryExpression()
   */
  public R visit(CompareExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "+"
   * f2 -> PrimaryExpression()
   */
  public R visit(PlusExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "-"
   * f2 -> PrimaryExpression()
   */
  public R visit(MinusExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "*"
   * f2 -> PrimaryExpression()
   */
  public R visit(TimesExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression() <-- array (read)
   * f1 -> "["
   * f2 -> PrimaryExpression() <-- index (read)
   * f3 -> "]"
   */
  public R visit(ArrayLookup n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f2.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression()
   * f1 -> "."
   * f2 -> "length"
   */
  public R visit(ArrayLength n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> PrimaryExpression() <-- object (read)
   * f1 -> "."
   * f2 -> Identifier() <-- method name (NOT a variable)
   * f3 -> "("
   * f4 -> ( ExpressionList() )?
   * f5 -> ")"
   */
  public R visit(MessageSend n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    // Skip f2 -- it is a method name, not a variable reference
    n.f4.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> Expression()
   * f1 -> ( ExpressionRest() )*
   */
  public R visit(ExpressionList n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> ","
   * f1 -> Expression()
   */
  public R visit(ExpressionRest n, A argu) {
    R _ret = null;
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> IntegerLiteral()
   * | TrueLiteral()
   * | FalseLiteral()
   * | Identifier()
   * | ThisExpression()
   * | ArrayAllocationExpression()
   * | AllocationExpression()
   * | NotExpression()
   * | BracketExpression()
   */
  public R visit(PrimaryExpression n, A argu) {
    R _ret = null;
    n.f0.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> <INTEGER_LITERAL>
   */
  public R visit(IntegerLiteral n, A argu) {
    return null;
  }

  /**
   * f0 -> "true"
   */
  public R visit(TrueLiteral n, A argu) {
    return null;
  }

  /**
   * f0 -> "false"
   */
  public R visit(FalseLiteral n, A argu) {
    return null;
  }

  /**
   * f0 -> <IDENTIFIER>
   *
   * This is the core read-check. When an Identifier appears in an expression
   * context (PrimaryExpression -> Identifier), it is a READ of that variable.
   * If it's a local var that hasn't been initialized yet, flag it.
   *
   * NOTE: We never call this from LHS contexts (AssignmentStatement,
   * ForStatement) -- those extract the name directly and handle it themselves.
   * We also skip Identifiers inside Type() and MessageSend's method name.
   */
  public R visit(Identifier n, A argu) {
    R _ret = null;
    String name = n.f0.tokenImage;
    // Only check variables we're tracking (local vars in this method)
    if (inMethodScope && localVars.contains(name) && !initializedVars.contains(name)) {
      uninitializedUsed = true;
    }
    return _ret;
  }

  /**
   * f0 -> "this"
   */
  public R visit(ThisExpression n, A argu) {
    return null;
  }

  /**
   * f0 -> "new"
   * f1 -> "int"
   * f2 -> "["
   * f3 -> Expression()
   * f4 -> "]"
   */
  public R visit(ArrayAllocationExpression n, A argu) {
    R _ret = null;
    n.f3.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "new"
   * f1 -> Identifier() <-- class name, NOT a variable
   * f2 -> "("
   * f3 -> ")"
   */
  public R visit(AllocationExpression n, A argu) {
    // f1 is a class name, not a variable -- skip it
    return null;
  }

  /**
   * f0 -> "!"
   * f1 -> ( MessageSend() | PrimaryExpression() )
   */
  public R visit(NotExpression n, A argu) {
    R _ret = null;
    n.f1.accept(this, argu);
    return _ret;
  }

  /**
   * f0 -> "("
   * f1 -> Expression()
   * f2 -> ")"
   */
  public R visit(BracketExpression n, A argu) {
    R _ret = null;
    n.f1.accept(this, argu);
    return _ret;
  }

}