//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;
import visitor.SymbolTableBuilder.ClassInfo;
import visitor.SymbolTableBuilder.MethodInfo;
import visitor.SymbolTableBuilder.SymbolTable;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 */
public class GJDepthFirst implements GJVisitor<String, String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if (n.present()) {
         String _ret = null;
         int _count = 0;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            e.nextElement().accept(this, argu);
            _count++;
         }
         return _ret;
      } else
         return null;
   }

   public String visit(NodeOptional n, String argu) {
      if (n.present())
         return n.node.accept(this, argu);
      else
         return null;
   }

   public String visit(NodeSequence n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) {
      return null;
   }

   //
   // User-generated visitor methods below
   //

   Integer temp = 0;
   HashMap<String, String> tempMap;

   String getTemp() {
      return "TEMP_" + temp++;
   }

   String currClass;
   String currMethod;

   SymbolTable ST;

   public GJDepthFirst(SymbolTable ST) {
      this.ST = ST;
   }

   String exps = "";

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public String visit(MainClass n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String id1 = n.f1.accept(this, argu);
      currClass = id1;
      tempMap = new HashMap<>();
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      currMethod = "main";
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      String id2 = n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      System.out.println("class " + id1 + " {\n" + "public static void main(String[] " + id2 + ") {");
      tempMap = new HashMap<>();
      String stmt = n.f14.accept(this, argu);
      for (Map.Entry<String, String> entry : tempMap.entrySet()) {
         System.out.println(entry.getValue() + " " + entry.getKey() + ";");
      }
      System.out.println(stmt);
      System.out.println("}\n}\n");
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    * | ClassExtendsDeclaration()
    */
   public String visit(TypeDeclaration n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( SimpleVarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public String visit(ClassDeclaration n, String argu) {
      String _ret = null;
      String id = n.f1.accept(this, argu);
      currClass = id;
      System.out.println("class " + id + " {");

      if (n.f3.present()) {
         for (int i = 0; i < n.f3.size(); i++) {
            String varDecl = n.f3.elementAt(i).accept(this, argu);
            if (varDecl != null) {
               System.out.print(varDecl);
            }
         }
      }

      if (n.f4.present()) {
         for (int i = 0; i < n.f4.size(); i++) {
            String methodDecl = n.f4.elementAt(i).accept(this, argu);
            if (methodDecl != null) {
               System.out.print(methodDecl);
            }
         }
      }
      System.out.println("}\n");
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( SimpleVarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public String visit(ClassExtendsDeclaration n, String argu) {
      String _ret = null;
      String id1 = n.f1.accept(this, argu);
      currClass = id1;

      String id2 = n.f3.accept(this, argu);
      System.out.println("class " + id1 + " extends " + id2 + " {");
      if (n.f5.present()) {
         for (int i = 0; i < n.f5.size(); i++) {
            String varDecl = n.f5.elementAt(i).accept(this, argu);
            if (varDecl != null) {
               System.out.print(varDecl);
            }
         }
      }
      if (n.f6.present()) {
         for (int i = 0; i < n.f6.size(); i++) {
            String methodDecl = n.f6.elementAt(i).accept(this, argu);
            if (methodDecl != null) {
               System.out.print(methodDecl);
            }
         }
      }
      System.out.println("}\n");
      return _ret;
   }

   /**
    * f0 -> SimpleVarDeclaration()
    * | FinalVarDeclaration()
    */
   public String visit(VarDeclaration n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public String visit(SimpleVarDeclaration n, String argu) {
      String _ret = null;
      String type = n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      System.out.println(type + " " + id + ";");
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "final"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public String visit(FinalVarDeclaration n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String type = n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String exp = n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      System.out.println(type + " " + id + " = " + exp + ";");
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n, String argu) {
      String _ret = null;
      tempMap = new HashMap<>();

      n.f0.accept(this, argu);
      String type = n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      currMethod = id;

      n.f3.accept(this, argu);
      String params = n.f4.accept(this, argu);
      if (params == null) {
         params = "";
      }
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      String bodyStmts = "";
      if (n.f8.present()) {
         for (int i = 0; i < n.f8.size(); i++) {
            String s = n.f8.elementAt(i).accept(this, argu);
            if (s != null) {
               bodyStmts += s;
            }
         }
      }

      n.f9.accept(this, argu);
      String exp = n.f10.accept(this, argu);

      String nerTEmp = getTemp();
      tempMap.put(nerTEmp, type);

      System.out.println("public " + type + " " + id + " (" + params + ") {");
      n.f7.accept(this, argu);

      for (Map.Entry<String, String> entry : tempMap.entrySet()) {
         System.out.println(entry.getValue() + " " + entry.getKey() + ";");
      }

      System.out.print(bodyStmts);
      System.out.println(nerTEmp + " = " + exp + ";");
      System.out.println("return " + nerTEmp + ";\n}\n");

      n.f11.accept(this, argu);
      n.f12.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public String visit(FormalParameterList n, String argu) {
      String param = n.f0.accept(this, argu);
      StringBuilder paramLst = new StringBuilder(param);

      if (n.f1.present()) {
         for (int i = 0; i < n.f1.size(); i++) {
            String rest = n.f1.elementAt(i).accept(this, argu);
            paramLst.append(rest);
         }
      }

      return paramLst.toString();
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public String visit(FormalParameter n, String argu) {
      String _ret = null;
      String type = n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      return type + " " + id;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public String visit(FormalParameterRest n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String param = n.f1.accept(this, argu);
      return ", " + param;
   }

   /**
    * f0 -> ArrayType()
    * | BooleanType()
    * | IntegerType()
    * | Identifier()
    */
   public String visit(Type n, String argu) {
      String _ret = null;
      String type = n.f0.accept(this, argu);
      return type;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public String visit(ArrayType n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return "int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public String visit(BooleanType n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return "boolean";
   }

   /**
    * f0 -> "int"
    */
   public String visit(IntegerType n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return "int";
   }

   /**
    * f0 -> Block()
    * | AssignmentStatement()
    * | ArrayAssignmentStatement()
    * | FieldAssignmentStatement()
    * | IfStatement()
    * | WhileStatement()
    * | ForStatement()
    * | PrintStatement()
    */
   public String visit(Statement n, String argu) {
      String _ret = null;
      String stmt = n.f0.accept(this, argu);
      return stmt;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public String visit(Block n, String argu) {
      String ret = "{\n";
      n.f0.accept(this, argu);

      if (n.f1.present()) {
         for (int i = 0; i < n.f1.size(); i++) {
            String stmt = n.f1.elementAt(i).accept(this, argu);

            if (stmt != null) {
               ret = ret + stmt + "\n";
            }
         }
      }

      n.f2.accept(this, argu);
      ret = ret + "}";

      return ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public String visit(AssignmentStatement n, String argu) {
      String _ret = null;
      String id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      String ret = exps + id + " = " + exp + ";\n";
      exps = "";
      n.f3.accept(this, argu);
      return ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public String visit(ArrayAssignmentStatement n, String argu) {
      String _ret = null;
      String id = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp1 = n.f2.accept(this, argu);
      String newTemp1 = getTemp();
      tempMap.put(newTemp1, "int");
      String ret = (exps = newTemp1 + " = " + exp1 + ";\n");
      exps = "";
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String exp2 = n.f5.accept(this, argu);
      String newTemp2 = getTemp();
      tempMap.put(newTemp2, "int");
      ret = ret + (newTemp2 + " = " + exp2 + ";\n");
      n.f6.accept(this, argu);
      ret = ret + (id + "[" + newTemp1 + "] = " + newTemp2 + ";\n");
      return ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    */
   public String visit(FieldAssignmentStatement n, String argu) {
      String _ret = null;
      String exp1 = n.f0.accept(this, argu);
      String newTemp1 = getTemp();
      String type = ST.classes.get(currClass).fields.get(n.f2.toString());
      tempMap.put(newTemp1, type);
      String ret = (exps + newTemp1 + " = " + exp1 + ";\n");
      exps = "";
      n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String exp2 = n.f4.accept(this, argu);
      String newTemp2 = getTemp();
      tempMap.put(newTemp2, type);
      ret = ret + (newTemp2 + " = " + exp2 + ";\n");
      n.f5.accept(this, argu);
      ret = ret + (newTemp1 + "." + id + " = " + newTemp2 + ";\n");
      return ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public String visit(IfStatement n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      String newTemp = getTemp();
      tempMap.put(newTemp, "boolean");
      String ret = (exps + newTemp + " = " + exp + ";\n");
      exps = "";
      n.f3.accept(this, argu);
      ret = ret + ("if (" + newTemp + ") {\n");
      ret = ret + n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      ret = ret + ("} else {\n");
      ret = ret + n.f6.accept(this, argu);
      ret = ret + ("}");
      return ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(WhileStatement n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String newTemp = getTemp();
      tempMap.put(newTemp, "boolean");
      String ret = (exps + newTemp + " = " + exp + ";\n");
      exps = "";
      ret = ret + ("while(" + newTemp + ") {\n");
      ret = ret + n.f4.accept(this, argu);
      ret = ret + newTemp + " = " + exp + ";\n}";
      return ret;
   }

   /**
    * f0 -> "for"
    * f1 -> "("
    * f2 -> Identifier()
    * f3 -> "="
    * f4 -> Expression()
    * f5 -> ";"
    * f6 -> Expression()
    * f7 -> ";"
    * f8 -> Identifier()
    * f9 -> "="
    * f10 -> Expression()
    * f11 -> ")"
    * f12 -> Statement()
    */
   public String visit(ForStatement n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String init = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String expInit = n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      String cond = n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      String loop = n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      String expLoop = n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      String ret = exps + "for( " + init + " = " + expInit + "; " + cond + "; " + loop + " = " + expLoop + ")";
      exps = "";
      n.f12.accept(this, argu);
      return ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public String visit(PrintStatement n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      String newTEmp = getTemp();
      tempMap.put(newTEmp, "int");
      String ret = exps;
      exps = "";
      ret = ret + newTEmp + " = " + exp + ";\n";
      n.f4.accept(this, argu);
      ret = ret + "System.out.println(" + newTEmp + ");";
      return ret;
   }

   /**
    * f0 -> AndExpression()
    * | CompareExpression()
    * | PlusExpression()
    * | MinusExpression()
    * | TimesExpression()
    * | ArrayLookup()
    * | ArrayLength()
    * | MessageSend()
    * | PrimaryExpression()
    */
   public String visit(Expression n, String argu) {
      String _ret = null;
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&"
    * f2 -> PrimaryExpression()
    */
   public String visit(AndExpression n, String argu) {
      String _ret = null;
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + " & " + P2;

      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<"
    * f2 -> PrimaryExpression()
    */
   public String visit(CompareExpression n, String argu) {
      String _ret = null;
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + " < " + P2;
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public String visit(PlusExpression n, String argu) {
      String _ret = null;
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + " + " + P2;
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public String visit(MinusExpression n, String argu) {
      String _ret = null;
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + " - " + P2;
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public String visit(TimesExpression n, String argu) {
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + " * " + P2;
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public String visit(ArrayLookup n, String argu) {
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + "[" + P2 + "]";
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public String visit(ArrayLength n, String argu) {
      String P1 = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String P2 = n.f2.accept(this, argu);
      String exp = P1 + "." + P2;
      return exp;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public String visit(MessageSend n, String argu) {
      String temp = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      String expList = n.f4.accept(this, argu);
      if (expList == null)
         expList = "";
      String exp = temp + "." + id + "(" + expList + ")";
      return exp;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public String visit(ExpressionList n, String argu) {
      String exp = n.f0.accept(this, argu);
      StringBuilder expList = new StringBuilder(exp);

      if (n.f1.present()) {
         for (int i = 0; i < n.f1.size(); i++) {
            String rest = n.f1.elementAt(i).accept(this, argu);
            expList.append(rest);
         }
      }

      return expList.toString();
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public String visit(ExpressionRest n, String argu) {
      String _ret = null;
      String exp = n.f1.accept(this, argu);
      return ", " + exp;
   }

   /**
    * f0 -> IntegerLiteral()
    * | TrueLiteral()
    * | FalseLiteral()
    * | Identifier()
    * | ThisExpression()
    * | ArrayAllocationExpression()
    * | AllocationExpression()
    * | NotExpression()
    * | BracketExpression()
    */
   public String visit(PrimaryExpression n, String argu) {
      String _ret = null;
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      return n.f0.toString();
   }

   /**
    * f0 -> "true"
    */
   public String visit(TrueLiteral n, String argu) {
      return n.f0.toString();
   }

   /**
    * f0 -> "false"
    */
   public String visit(FalseLiteral n, String argu) {
      return n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Identifier n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> "this"
    */
   public String visit(ThisExpression n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public String visit(ArrayAllocationExpression n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String temp = n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String newTemp = getTemp();
      tempMap.put(newTemp, "int[]");

      exps += newTemp + " = new int[" + temp + "];\n";
      return newTemp;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public String visit(AllocationExpression n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String newTemp = getTemp();
      tempMap.put(newTemp, id);
      exps += newTemp + " = new " + id + "();\n";
      return newTemp;
   }

   /**
    * f0 -> "!"
    * f1 -> ( MessageSend() | PrimaryExpression() )
    */
   public String visit(NotExpression n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      String temp1 = getTemp();
      tempMap.put(temp1, "boolean");
      exps += temp1 + " = " + exp + ";\n";
      String temp2 = getTemp();
      tempMap.put(temp2, "boolean");
      exps += temp2 + " = !" + temp1 + ";\n";

      return temp2;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public String visit(BracketExpression n, String argu) {
      String exp = n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      // String newTemp = getTemp();
      // System.out.println(newTemp + " = ( " + exp + " )");
      return exp;
   }

}
